
project_id = "hziwbeyokjdswlzzmjem"

[functions.keep-alive]
verify_jwt = false

[functions.scheduled-query]
verify_jwt = false

[functions.user-stats]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false
